[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Pinned by rkyv.
ptr_meta = "~0.1.3"
rkyv = "0.7.44"
rkyv_dyn = "0.7.44"
rkyv_typename = "0.7.44"
