name: Rust

on:
  push:
    branches: ["main", "ci-cd"]
    paths:
      - ".github/workflows/**"
      - "Cargo.*"
      - "*/Cargo.*"
      - "*/src/**.rs"
  pull_request:
    branches: ["main", "ci-cd"]
    paths:
      - ".github/workflows/**"
      - "Cargo.*"
      - "*/Cargo.*"
      - "*/src/**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update --no-self-update nightly
      - run: cargo +nightly test --verbose

  mutants:
    # From: https://mutants.rs/ci.html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-mutants, cargo-nextest
      - run: rustup update --no-self-update nightly
      - run: cargo +nightly mutants --test-tool=nextest -vV --in-place
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out
