name: Slow Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  mutants:
    # From: https://mutants.rs/ci.html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: "rust-workspace/"
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-mutants, cargo-nextest
      - run: rustup update --no-self-update nightly
      - run: cargo +nightly -Z unstable-options -C rust-workspace mutants --test-tool=nextest -vV --in-place
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out
